### ISSUE TITLE
I found a problem in the script.

### ISSUE THREAD

**Issue by Apache553** [fuzzzzzz/MESA#3]
I'm Chinese.My English is really bad.so please dont laugh at me.

When I run the script,Script Editor shows me this:
```
source smdOptionWindow;
smdOptionWindow;
// ERROR: 		$list[$cnt] = \`substitute "? $item "" \`; //
// ERROR: "E:/MESA/scripts/smdExport.mel" line 19.43: Unterminated string. //
```
There is nothing happened.

than I try to fix it,so I change 
```
$list[$cnt] = `substitute "? $item "" `
```
to 
```
$list[$cnt] = `substitute "?" $item "" `
```
than it works well.

This code looks right in the webpage of Github.(I haven't learnt Mel.)
I'm using "Maya 2015 64 bit".
please fix it.

**Comment by fuzzzzzz** [comment]
Hello Apache, thank you for reporting, 
i am aware of that issue, there is a workaround : 

> Go to control panel -> region and language -> language for non-unicode
> After changing this to English(United States), everything works well.

**Comment by Apache553** [comment]
Thanks a lot!

I will tell it to others
